apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f php73.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: permissions
  name: permissions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: permissions
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f php73.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: permissions
    spec:
      containers:
      - image: esimonetti/sugardockerized:permissions-1.19
        imagePullPolicy: ""
        name: sugar-permissions
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: permissions-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: permissions-claim0
        persistentVolumeClaim:
          claimName: permissions-claim0
status: {}
