apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f php73.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: testsmtp
  name: testsmtp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: testsmtp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f php73.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: testsmtp
    spec:
      containers:
      - image: sugar_testsmtp
        imagePullPolicy: ""
        name: sugar-smtp
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
