apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f php73.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web1
  name: web1
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: web1
status:
  loadBalancer: {}
